create table if not exists public.answer_submissions (
  id bigint generated by default as identity primary key,
  session_id text not null,
  question_number integer not null check (question_number between 1 and 12),
  question_text text not null default '',
  answer_text text not null check (char_length(answer_text) between 1 and 5000),
  is_correct boolean not null default false,
  submitted_at timestamptz not null default now(),
  user_agent text not null default ''
);

create index if not exists answer_submissions_submitted_at_idx
  on public.answer_submissions (submitted_at desc);

create index if not exists answer_submissions_question_number_idx
  on public.answer_submissions (question_number);

alter table public.answer_submissions enable row level security;

revoke all on table public.answer_submissions from anon, authenticated;
grant insert on table public.answer_submissions to anon, authenticated;
grant select on table public.answer_submissions to authenticated;
grant usage, select on sequence public.answer_submissions_id_seq to anon, authenticated;

drop policy if exists "Anyone can submit answers" on public.answer_submissions;
create policy "Anyone can submit answers"
on public.answer_submissions
for insert
to anon, authenticated
with check (
  question_number between 1 and 12
  and char_length(answer_text) between 1 and 5000
  and char_length(session_id) between 1 and 100
);

drop policy if exists "Only owner can read answers" on public.answer_submissions;
create policy "Only owner can read answers"
on public.answer_submissions
for select
to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'rzouh1p@gmail.com');
